### ISSUE TITLE
Question about async and await

### ISSUE THREAD

**Issue by winterjung** [Luavis/GDG-Devcamp-2016#1]
```python
async def _handle(reader, writer):
    status_line = (await reader.readuntil(b'\r\n')).decode('ascii')[:-2]
```
이라는 구문에서 `await`를 하는 대상이 `reader.readuntil()` 인데
이 `reader.readuntil()` 은 `future` (`task`인지 `future`인지...)를 반환하기때문에 이 결과값을 기다리려고 `await`를 명시한건가요?
그리고 위의 구문을
```python
async read(reader):
    return reader.readuntil(b'\r\n')).decode('ascii')[:-2]

async def _handle(reader, writer):
    status_line = (await read(reader))
```
로 바꿔줄 수 있나요?

**Comment by Luavis** [comment]
우선 확인해볼때는 `reader.readuntil`은 built-in되어 있는 generator가 return 되는데 중요한점은 여기서 사용하고 있는 reader는 [asyncio의 StreamReader](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.readuntil)가 받아지고 이는 await으로만 결과값을 대기해야합니다.

분리는 할 수 있습니다 다만 `reader.readuntil` 앞에 await 키워드는 붙여야합니다.

**Comment by winterjung** [comment]
그러면 말씀하신대로
```python
async def read(reader):
    return (await reader.readuntil(b'\r\n')).decode('ascii')[:-2])
```
로 별도의 함수로 분리하였는데
```python
async def _handle(reader, writer):
    status_line = (await read(reader))
```
이 부분을
```python
async def _handle(reader, writer):
    status_line = read(reader)
```
이렇게 써도 되는건지 아니면 그대로 `await`를 붙여 써야하는건지 궁금합니다.

**Comment by Luavis** [comment]
모든 async함수에는 await을 붙여야합니다.
